Add support thecodingmachine/graphqlite 5
thecodingmachine/graphqlite-laravel pull request #34
Opened 2021-11-08 11:22 UTC by DenisVinokurov

2021-11-09 15:16 UTC, devmaslov requested changes
@DenisVinokurov Thanks for the PR. Looks good to me, just a few tweaks are needed before merging.

2021-11-09 15:16 UTC, devmaslov commented on composer.json
> +        "php": ">=7.2|8.0",
No need to specify 8.0 version, since ">=7.2" covers it.

```suggestion
        "php": ">=7.2",
```

2021-11-09 15:16 UTC, devmaslov commented on composer.json
> +        "thecodingmachine/graphqlite": "^5",
```suggestion
        "thecodingmachine/graphqlite": "^5.0",
```

2021-11-10 03:39 UTC, DenisVinokurov commented
@devmaslov added fixes

2021-11-10 08:14 UTC, devmaslov approved these changes

2021-11-10 08:14 UTC, merged